#!/usr/bin/env bash
# =============================================================================
#  PayFlux - one-command start for macOS and Linux
#
#    ./run-payflux.sh
#
#  The Windows equivalent is RUN-PAYFLUX.bat (double-click it).
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

cyan()  { printf '\033[36m%s\033[0m\n' "$*"; }
gray()  { printf '\033[90m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
die()   { printf '\n\033[31mERROR: %s\033[0m\n\n' "$1"; shift; for l in "$@"; do gray "  $l"; done; echo; exit 1; }

echo
cyan "  ==========================================================="
echo  "    PayFlux - Distributed Payment Gateway"
cyan "  ==========================================================="
echo

# --- 1. Docker -------------------------------------------------------------
cyan "  [1/6] Checking Docker..."
command -v docker >/dev/null 2>&1 || die "Docker is not installed, or not on your PATH." \
  "Install Docker:  https://www.docker.com/products/docker-desktop" "Then re-run this script."
docker info >/dev/null 2>&1 || die "Docker is installed, but the engine is not running." \
  "Start Docker Desktop (or 'sudo systemctl start docker'), then re-run."
docker compose version >/dev/null 2>&1 || die "'docker compose' is unavailable." "Update Docker and re-run."
gray "        Docker is running."

# --- 2. Ports --------------------------------------------------------------
# Test by actually binding, which is exactly what Docker is about to do -
# more reliable than parsing lsof/netstat output.
cyan "  [2/6] Checking ports..."
free_port() {
  local p=$1 label=$2 i
  for ((i=0; i<60; i++)); do
    if node -e "const n=require('net'),s=n.createServer();s.once('error',()=>process.exit(1));s.once('listening',()=>s.close(()=>process.exit(0)));s.listen($p,'127.0.0.1')" 2>/dev/null; then
      [ "$p" != "$1" ] && gray "        Port $1 is in use - using $p for the $label." >&2
      echo "$p"; return
    fi
    p=$((p+1))
  done
  echo "$1"
}
if command -v node >/dev/null 2>&1; then
  API=$(free_port 4000 API);        CONSOLE=$(free_port 8080 console)
  STORE=$(free_port 8081 storefront); MONGO=$(free_port 27017 MongoDB)
  REDIS=$(free_port 6379 Redis)
else
  # No Node on the host - fall back to the defaults and let compose complain.
  API=4000; CONSOLE=8080; STORE=8081; MONGO=27017; REDIS=6379
  gray "        Node not found on the host - using default ports."
fi
gray "        Ports resolved."

# --- 3. Configuration ------------------------------------------------------
cyan "  [3/6] Preparing configuration..."
if [ -f .env ]; then
  gray "        Existing .env found - keeping your settings."
  API=$(grep -E '^API_PORT='        .env | cut -d= -f2 || echo "$API")
  CONSOLE=$(grep -E '^CONSOLE_PORT='    .env | cut -d= -f2 || echo "$CONSOLE")
  STORE=$(grep -E '^STOREFRONT_PORT=' .env | cut -d= -f2 || echo "$STORE")
else
  # 32 random bytes as hex = 64 chars; the config layer rejects anything under 32.
  secret() {
    if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32
    else node -pe "require('crypto').randomBytes(32).toString('hex')"; fi
  }
  cat > .env <<EOF
# Generated by run-payflux.sh - do not commit this file.
JWT_SECRET=$(secret)
JWT_REFRESH_SECRET=$(secret)

API_PORT=$API
CONSOLE_PORT=$CONSOLE
STOREFRONT_PORT=$STORE
MONGO_PORT=$MONGO
REDIS_PORT_HOST=$REDIS
EOF
  gray "        Generated .env with fresh secrets."
fi

# --- 4. Build and start ----------------------------------------------------
cyan "  [4/6] Building and starting containers..."
gray "        First run pulls images and builds - allow 3-5 minutes."
echo
docker compose up -d --build || die "docker compose failed (see the output above)." \
  "Common causes: no internet for the image pull, a port taken after the check," \
  "or Docker out of disk/memory."
echo

# --- 5. Wait for health ----------------------------------------------------
cyan "  [5/6] Waiting for services to become healthy..."
healthy=false
for i in $(seq 1 60); do
  if [ "$(docker inspect --format '{{.State.Health.Status}}' payflux-api 2>/dev/null || echo none)" = "healthy" ]; then
    healthy=true; break
  fi
  [ "$i" = "10" ] && gray "        Still starting (MongoDB elects its replica set first)..."
  sleep 3
done
$healthy && gray "        API is healthy." || {
  gray "        WARNING: not healthy within ~3 minutes."
  gray "        Check:  docker compose ps    Logs: docker compose logs api"
}

# --- 6. Demo data ----------------------------------------------------------
cyan "  [6/6] Checking demo data..."
PROBE='const m=require("mongoose");(async()=>{try{await m.connect(process.env.MONGO_URI);const n=await m.connection.db.collection("users").countDocuments();await m.disconnect();process.exit(n>0?0:1)}catch(e){process.exit(1)}})()'
if docker compose exec -T api node -e "$PROBE" >/dev/null 2>&1; then
  gray "        Demo data already present - skipping seed."
else
  gray "        Seeding demo data (420 payments, ledger, fraud alerts)..."
  docker compose exec -T api npm run seed
fi

# --- Summary ---------------------------------------------------------------
echo
green "  ==========================================================="
green "    PayFlux is running"
green "  ==========================================================="
echo
printf "    Storefront  (buy something)    \033[36mhttp://localhost:%s\033[0m\n" "$STORE"
printf "    Console     (admin dashboard)  \033[36mhttp://localhost:%s\033[0m\n" "$CONSOLE"
printf "    Swagger     (API docs)         \033[36mhttp://localhost:%s/api/docs\033[0m\n" "$API"
printf "    Health                         \033[36mhttp://localhost:%s/health\033[0m\n" "$API"
echo
echo  "    Sign in with (password PayFlux#2024 for all):"
gray  "      ADMIN     admin@payflux.io"
gray  "      MERCHANT  merchant@nimbusretail.example"
gray  "      SUPPORT   support@payflux.io"
echo
echo  "    Stop:  docker compose down"
echo  "    Logs:  docker compose logs -f api"
echo
green "  ==========================================================="
echo

# Open a browser where we can, without failing the script if we cannot.
if command -v open    >/dev/null 2>&1; then open "http://localhost:$STORE" 2>/dev/null || true
elif command -v xdg-open >/dev/null 2>&1; then xdg-open "http://localhost:$STORE" 2>/dev/null || true
fi
