'use strict';

/**
 * Demo merchant storefront — the *shop's* backend.
 *
 * ── Why this server exists at all ──────────────────────────────────────────
 * The browser must never hold merchant API credentials. If the checkout page
 * called PayFlux directly, the merchant's token would be sitting in front-end
 * JavaScript for anyone to read, and a customer could mint payments, issue
 * refunds, or read every other customer's transactions.
 *
 * So the flow is the one a real integration uses:
 *
 *   browser  →  this shop server (holds the credentials)  →  PayFlux API
 *
 * The browser only ever sees a cart and an outcome. It never sees a token, and
 * it never gets to choose the amount — the price is looked up server-side from
 * the catalogue, because a client-supplied price is a client-controlled price.
 */

const express = require('express');
const crypto = require('node:crypto');

const app = express();
app.use(express.json({ limit: '32kb' }));
app.use(express.static('public'));

const PAYFLUX_API = process.env.PAYFLUX_API || 'http://localhost:4000/api/v1';
const MERCHANT_EMAIL = process.env.MERCHANT_EMAIL || 'merchant@nimbusretail.example';
const MERCHANT_PASSWORD = process.env.MERCHANT_PASSWORD || 'PayFlux#2024';
const PORT = Number(process.env.PORT || 8081);

/**
 * The catalogue is the source of truth for prices.
 * Amounts are integer minor units (paise) — never floats. See the PayFlux
 * money docs for why.
 */
const CATALOGUE = [
  { sku: 'NR-HDPH-01', name: 'Aurora Wireless Headphones', priceMinor: 249900, emoji: '🎧',
    blurb: 'Active noise cancelling · 40h battery' },
  { sku: 'NR-KEYB-02', name: 'Meridian Mechanical Keyboard', priceMinor: 1299900, emoji: '⌨️',
    blurb: 'Hot-swappable · tactile browns' },
  { sku: 'NR-MOUS-03', name: 'Vector Ergonomic Mouse', priceMinor: 74900, emoji: '🖱️',
    blurb: 'Vertical grip · 8000 DPI' },
  { sku: 'NR-CABL-04', name: 'Braided USB-C Cable', priceMinor: 4900, emoji: '🔌',
    blurb: '2m · 100W passthrough' },
];

// ── PayFlux credentials, cached server-side ──────────────────────────────
let tokenCache = { accessToken: null, expiresAt: 0 };

/** Log in to PayFlux and cache the token until shortly before it expires. */
async function getToken() {
  if (tokenCache.accessToken && Date.now() < tokenCache.expiresAt) {
    return tokenCache.accessToken;
  }
  const res = await fetch(`${PAYFLUX_API}/auth/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ email: MERCHANT_EMAIL, password: MERCHANT_PASSWORD }),
  });
  const body = await res.json();
  if (!body.success) throw new Error(`PayFlux login failed: ${body.error?.message}`);

  tokenCache = {
    accessToken: body.data.accessToken,
    // Access tokens live 15 minutes; refresh at 12 to leave headroom.
    expiresAt: Date.now() + 12 * 60 * 1000,
  };
  return tokenCache.accessToken;
}

/** Call PayFlux, retrying once on a 401 in case the cached token went stale. */
async function payflux(path, { method = 'GET', body, idempotencyKey, retry = true } = {}) {
  const token = await getToken();
  const res = await fetch(PAYFLUX_API + path, {
    method,
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${token}`,
      ...(idempotencyKey ? { 'idempotency-key': idempotencyKey } : {}),
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });

  if (res.status === 401 && retry) {
    tokenCache = { accessToken: null, expiresAt: 0 };
    return payflux(path, { method, body, idempotencyKey, retry: false });
  }

  return {
    status: res.status,
    replayed: res.headers.get('x-idempotent-replay') === 'true',
    retryable: res.headers.get('x-retryable') === 'true',
    body: await res.json(),
  };
}

// ── Routes ────────────────────────────────────────────────────────────────

app.get('/api/catalogue', (_req, res) => res.json({ products: CATALOGUE }));

/**
 * Checkout.
 *
 * The browser sends *what* was ordered, never *how much* it costs. The total is
 * computed here from the catalogue, so a tampered request cannot buy a
 * ₹12,999 keyboard for ₹1.
 */
app.post('/api/checkout', async (req, res) => {
  const { items = [], customer = {}, idempotencyKey } = req.body;

  const lines = [];
  for (const item of items) {
    const product = CATALOGUE.find((p) => p.sku === item.sku);
    if (!product) return res.status(400).json({ error: `Unknown SKU: ${item.sku}` });
    const quantity = Math.max(1, Math.min(10, Number(item.quantity) || 1));
    lines.push({ ...product, quantity, lineTotalMinor: product.priceMinor * quantity });
  }
  if (!lines.length) return res.status(400).json({ error: 'Cart is empty' });

  const totalMinor = lines.reduce((sum, line) => sum + line.lineTotalMinor, 0);

  // One key per checkout attempt, generated by the shop. Re-sending the same
  // key is what makes a retry safe — and the front end deliberately exposes a
  // button to do exactly that, so the guarantee is visible.
  const key = idempotencyKey || `shop-${crypto.randomUUID()}`;

  try {
    const result = await payflux('/payments', {
      method: 'POST',
      idempotencyKey: key,
      body: {
        amountMinor: totalMinor,
        currency: 'INR',
        method: customer.method || 'CARD',
        customer: {
          customerId: customer.customerId || undefined,
          email: customer.email || undefined,
          contact: customer.contact || undefined,
          last4: customer.last4 || undefined,
          country: customer.country || 'IN',
        },
        description: lines.map((l) => `${l.quantity}× ${l.name}`).join(', ').slice(0, 500),
        notes: { orderRef: key.slice(0, 40), channel: 'web' },
      },
    });

    const payment = result.body.data;
    const error = result.body.error;

    return res.json({
      httpStatus: result.status,
      idempotencyKey: key,
      replayed: result.replayed,
      retryable: result.retryable,
      totalMinor,
      lines: lines.map((l) => ({ name: l.name, quantity: l.quantity, lineTotalMinor: l.lineTotalMinor })),
      payment: payment ?? null,
      error: error ?? null,
      correlationId: result.body.meta?.correlationId ?? null,
    });
  } catch (err) {
    // The gateway itself is unreachable — distinct from a declined card.
    return res.status(502).json({ error: `Cannot reach the payment gateway: ${err.message}` });
  }
});

/** Poll a payment that came back PROCESSING. Safe to call repeatedly. */
app.post('/api/verify/:paymentId', async (req, res) => {
  const result = await payflux(`/payments/${req.params.paymentId}/verify`, {
    method: 'POST', body: { reconcile: true },
  });
  return res.json({ payment: result.body.data ?? null, error: result.body.error ?? null });
});

app.get('/api/payment/:paymentId', async (req, res) => {
  const result = await payflux(`/payments/${req.params.paymentId}`);
  return res.json({ payment: result.body.data ?? null, error: result.body.error ?? null });
});

app.get('/healthz', (_req, res) => res.json({ status: 'ok', gateway: PAYFLUX_API }));

app.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`Nimbus Retail storefront on http://localhost:${PORT}  →  gateway ${PAYFLUX_API}`);
});
